
// swift-tools-version:5.3
import PackageDescription


// This file is generated by GH-action push_swift_package_manager_version.yml
// From repo https://github.com/CUEAudio/LightShow_iOS
// Don't edit it manually

let package = Package(
    name: "CUELive",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        .library(
            name: "CUELive",
            targets: ["CUELive", "CUEBluetooth", "engine"]
        ),
    ],
    targets: [
		.binaryTarget(
			name: "CUELive",
			url: "https://s3.amazonaws.com/swift-package-manager/binaries/CUELive/3.11.6/CUELive.3.11.6.xcframework.zip",
			checksum: "b785e965afb6c24bb0ae634e440c745ac143867bf1a5d1f3476d7d0a2f10501d"
		),
		.binaryTarget(
			name: "CUEBluetooth",
			url: "https://s3.amazonaws.com/swift-package-manager/binaries/CUEBluetooth/0.0.17/CUEBluetooth.0.0.17.xcframework.zip",
			checksum: "3937a448be41f69b82f1376a4bd6a965dd023aae58102d3cd827a544b2fa47c4"
		),
		.binaryTarget(
			name: "engine",
			url: "https://s3.amazonaws.com/swift-package-manager/binaries/engine/1.69.1/engine.1.69.1.xcframework.zip",
			checksum: "e91cd98f9560c25a4129c614d19c10103cb61ba4b3acc913f202801f5793e382"
		)
	]
)
